name: Rust

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-22.04', 'windows-2022']
    runs-on: '${{ matrix.os }}'

    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install dependencies (ubuntu only)
        if: ${{ contains(matrix.os, 'ubuntu') }}
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: 'rust-v0'

      - name: Build
        run: yarn && yarn tauri build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: 'parakeet-desktop-${{ matrix.os }}'
          path: 'src-tauri/target/release/Parakeet Desktop*'

      - name: Upload Windows Installer
        if: ${{ contains( matrix.os, 'windows' ) }}
        uses: actions/upload-artifact@v3.1.1
        with:
          name: 'parakeet-desktop-installer-${{ matrix.os }}'
          path: 'src-tauri/target/release/bundle/msi/*.msi'
